// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNgdrSkwWKACjKBqYMoJeVjmIdEQBk9Jo',
    appId: '1:784859592636:web:e412c724240644de4b1db9',
    messagingSenderId: '784859592636',
    projectId: 'emaus-db',
    authDomain: 'emaus-db.firebaseapp.com',
    storageBucket: 'emaus-db.appspot.com',
    measurementId: 'G-21GJNCVLR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8BN1lUqtxJiGgkI4AFXouIJcj1cA2Jgs',
    appId: '1:784859592636:android:4ce64cca6171d3094b1db9',
    messagingSenderId: '784859592636',
    projectId: 'emaus-db',
    storageBucket: 'emaus-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5ErKjm7YHwQ4Kh-fcwLbz5azc0sSNsU',
    appId: '1:784859592636:ios:a53b3c07aec38cdf4b1db9',
    messagingSenderId: '784859592636',
    projectId: 'emaus-db',
    storageBucket: 'emaus-db.appspot.com',
    iosClientId: '784859592636-7dnvkiva3hp8k17s4lfu8tq2jfqp6hed.apps.googleusercontent.com',
    iosBundleId: 'com.example.emmausapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh5ErKjm7YHwQ4Kh-fcwLbz5azc0sSNsU',
    appId: '1:784859592636:ios:3bb2e234fd31108e4b1db9',
    messagingSenderId: '784859592636',
    projectId: 'emaus-db',
    storageBucket: 'emaus-db.appspot.com',
    iosClientId: '784859592636-u5ca27gu8ean8t072imcv0dekll6rvec.apps.googleusercontent.com',
    iosBundleId: 'com.example.emmausapp.RunnerTests',
  );
}
